version: '3.1'

services:

  db:
    image: mongo:4
    command: --quiet
    networks:
      - webapp

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: docker.pkg.github.com/timboslicecreative/xstack/api
    ports:
      - 1337:1337
    depends_on:
      - db
    networks:
      - webapp

  thumbor:
    build:
      context: ./thumbor
      dockerfile: Dockerfile
    image: docker.pkg.github.com/timboslicecreative/xstack/thumbor
    networks:
      - webapp

  nginx:
    image: nginx:latest
    depends_on:
      - thumbor
    ports:
      - 3001:80
    networks:
      - webapp

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: docker.pkg.github.com/timboslicecreative/xstack/web
    ports:
      - 3000:3000
    depends_on:
      - api
      - nginx
    networks:
      - webapp

networks:
  webapp:
    driver: bridge

volumes:
  db: {}
  thumbor: {}
  media: {}
  media_cache: {}
  frontend_cache: {}
  logs: {}