version: '3.1'

services:

  db:
    image: mongo:4
    env_file:
      - db/db.env
    volumes:
      - db:/data/db
    command: --quiet
    networks:
      - webapp

  thumbor:
    image: apsl/thumbor:latest
    env_file:
      - thumbor/thumbor.env
    volumes:
      - thumbor:/data
      - media:/media
      - media_cache:/tmp/media_cache
    networks:
      - webapp

  nginx:
    image: nginx:latest
    depends_on:
      - thumbor
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - logs:/logs
    ports:
      - 3001:80
    networks:
      - webapp

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: docker.pkg.github.com/timboslicecreative/web-app/api
    env_file:
      - api/api.env
    volumes:
      - ./api/src:/srv/app
      - /srv/app/node_modules
      - /srv/app/.cache
      - /srv/app/build
    ports:
      - 1337:1337
    depends_on:
      - db
    networks:
      - webapp

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: docker.pkg.github.com/timboslicecreative/web-app/web
    env_file:
      - web/web.env
    volumes:
      - ./web/src:/srv/app
      - /srv/app/node_modules
      - /srv/app/.next
    ports:
      - 3000:3000
    depends_on:
      - api
      - nginx
    networks:
      - webapp

networks:
  webapp:
    driver: bridge

volumes:
  db: {}
  thumbor: {}
  media: {}
  media_cache: {}
  frontend_cache: {}
  logs: {}